INSERT INTO class (CREATED_DATE, isDeleted, UPDATED_DATE, CLASS_NAME, CREATED_BY)
VALUES ('2021-05-28 14:47:32.000000', 0, null, '18CTT3', null);

INSERT INTO class (CREATED_DATE, isDeleted, UPDATED_DATE, CLASS_NAME, CREATED_BY)
VALUES ('2021-05-28 14:47:46.000000', 0, null, '18CNTN', null);

INSERT INTO class (CREATED_DATE, isDeleted, UPDATED_DATE, CLASS_NAME, CREATED_BY)
VALUES ('2021-05-28 14:47:46.000000', 0, null, '18CTT1', null);

INSERT INTO class (CREATED_DATE, isDeleted, UPDATED_DATE, CLASS_NAME, CREATED_BY)
VALUES ('2021-05-28 14:47:46.000000', 0, null, '18CTT2', null);

INSERT INTO class (CREATED_DATE, isDeleted, UPDATED_DATE, CLASS_NAME, CREATED_BY)
VALUES ('2021-05-28 14:47:46.000000', 0, null, '18CTT4', null);

INSERT INTO class (CREATED_DATE, isDeleted, UPDATED_DATE, CLASS_NAME, CREATED_BY)
VALUES ('2021-05-28 14:47:46.000000', 0, null, '18CTT5', null);

INSERT INTO class (CREATED_DATE, isDeleted, UPDATED_DATE, CLASS_NAME, CREATED_BY)
VALUES ('2021-05-28 14:47:46.000000', 0, null, '18CTT6', null);

INSERT INTO class (CREATED_DATE, isDeleted, UPDATED_DATE, CLASS_NAME, CREATED_BY)
VALUES ('2021-05-28 14:47:46.000000', 0, null, '18CTT7', null);



INSERT INTO education_type (CREATED_DATE, isDeleted, UPDATED_DATE, NAME)
VALUES (null, 0, null, 'Chính quy');

INSERT INTO education_type (CREATED_DATE, isDeleted, UPDATED_DATE, NAME)
VALUES (null, 0, null, 'Từ Xa');

INSERT INTO education_type (CREATED_DATE, isDeleted, UPDATED_DATE, NAME)
VALUES (null, 0, null, 'Hoàn chỉnh');

INSERT INTO education_type (CREATED_DATE, isDeleted, UPDATED_DATE, NAME)
VALUES (null, 0, null, 'Chất lượng cao');

INSERT INTO education_type (CREATED_DATE, isDeleted, UPDATED_DATE, NAME)
VALUES (null, 0, null, 'Tiên tiến');

INSERT INTO education_type (CREATED_DATE, isDeleted, UPDATED_DATE, NAME)
VALUES (null, 0, null, 'Cao đẳng');

INSERT INTO student_info (CREATED_DATE, isDeleted, UPDATED_DATE, BIRTHDAY, FULL_NAME, GENDER, IDENTITY_CARD_NUMBER) VALUES ('2021-05-28 14:38:51.000000', 0, null, '1998-05-28 14:38:38.000000', 'Nguyễn Văn Trọng', 'Boy', '12345678')
INSERT INTO student_info (CREATED_DATE, isDeleted, UPDATED_DATE, BIRTHDAY, FULL_NAME, GENDER, IDENTITY_CARD_NUMBER) VALUES ('2021-05-28 14:39:02.000000', 0, null, '2000-05-28 14:42:41.000000', 'Nguyễn Văn Dũng', 'Boy', '00000000')
INSERT INTO student_info (CREATED_DATE, isDeleted, UPDATED_DATE, BIRTHDAY, FULL_NAME, GENDER, IDENTITY_CARD_NUMBER) VALUES ('2021-05-28 14:41:47.000000', 0, null, '1999-05-28 14:41:55.000000', 'Nguyễn Trọng Bình', 'Boy', '99999999')
INSERT INTO student_info (CREATED_DATE, isDeleted, UPDATED_DATE, BIRTHDAY, FULL_NAME, GENDER, IDENTITY_CARD_NUMBER) VALUES ('2021-05-28 14:42:33.000000', 0, null, '1999-05-28 14:42:46.000000', 'Nguyễn Thị Như Ngọc', 'Girl', '77777777')


INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('32331', null, 0, null, 3, 'Đại số tuyến tính');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('456', null, 0, null, 4, 'Nhập môn lập trình');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('789', null, 0, null, 3, 'Thể dục');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('1011', null, 0, null, 3, 'Anh văn 1');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('1234', null, 0, null, 3, 'Anh văn 2');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('123', null, 0, null, 3, 'Anh văn 3');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('112', null, 0, null, 2, 'Anh văn 4');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('222', null, 0, null, 4, 'Lập trình hướng đối tượng');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('333', null, 0, null, 4, 'Lập trình robot');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('225', null, 0, null, 3, 'Cơ sở dữ liệu');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('766', null, 0, null, 4, 'Độ phức tạp thuật toán');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('777', null, 0, null, 4, 'Nhập môn trí tuệ nhân tao');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('775', null, 0, null, 4, 'Mac Lennin');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('544', null, 0, null, 2, 'Thể dục 2');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('565', null, 0, null, 2, 'Kiến tập nghề thiệp');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('5454', null, 0, null, 3, 'Vi tích phân 1 B');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('45432', null, 0, null, 3, 'Nhập môn lập trình 2');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('343', null, 0, null, 4, 'Cơ sở dữ liệu nâng cao');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('4343', null, 0, null, 3, 'Lập trình web');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('3434', null, 0, null, 4, 'Lập trình android');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('343234', null, 0, null, 4, 'Lập trình windows');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('3432322', null, 0, null, 4, 'Phương pháp tính');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('34343', null, null, null, 4, 'Toán học tổ hợp');

INSERT INTO subject (SUBJECT_ID, CREATED_DATE, isDeleted, UPDATED_DATE, SUBJECT_CREDIT, SUBJECT_NAME)
VALUES ('3433', null, null, null, 3, 'Vi tích phân 2B');


INSERT INTO teaching_manager (TEACHING_MANAGER_ID, CREATED_DATE, isDeleted, UPDATED_DATE, PASSWORD, FULL_NAME)
VALUES ('12345678', '2021-05-28 14:37:20.000000', 0, null, '12345678', 'Nguyễn Văn Thật');

INSERT INTO teaching_manager (TEACHING_MANAGER_ID, CREATED_DATE, isDeleted, UPDATED_DATE, PASSWORD, FULL_NAME)
VALUES ('00000000', '2021-05-28 14:37:23.000000', 0, null, '00000000', 'Nguyễn Công Minh');
